# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Top"
  url = "#top"
  weight = 10

[[main]]
  name = "News"
  url = "#news"
  weight = 20

[[main]]
  name = "Vision"
  url = "#Vision"
  weight = 30

[[main]]
  name = "Environment"
  url = "#environment"
  weight = 40

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 50

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 60

[[main]]
  name = "Member"
  url = "#people"
  weight = 70

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
